### ISSUE TITLE
TypeError: Cannot read property 'toDevicePixels' of undefined

### ISSUE THREAD

**Issue by ChaDmiS** [nativescript-community/ui-persistent-bottomsheet#10]
Hello!

I install plugin and try it on iOS and Android. It works on iOS successfully. But on Android I get error:

  System.err: An uncaught Exception occurred on "main" thread.
  System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
  System.err: TypeError: Cannot read property 'toDevicePixels' of undefined
  System.err: File: (file: app/webpack:/vvf/node_modules/@nativescript-community/gesturehandler/gesturehandler.android.js:273:46)
  System.err:
  System.err: StackTrace:
  System.err: ./node_modules/@nativescript-community/gesturehandler/gesturehandler.android.js(file: app/webpack:/vvf/node_modules/@nativescript-community/gesturehandler/gesturehandler.android.js:273:46)
  System.err:   at __webpack_require__(file: app/webpack:/vvf/webpack/bootstrap:19:0)
  System.err:   at ./node_modules/@nativescript-community/ui-persistent-bottomsheet/index.js(file:///data/data/org.nativescript.exampleapp/files/app/vendor.js:3891:96)
  System.err:   at __webpack_require__(file: app/webpack:/vvf/webpack/bootstrap:19:0)
  System.err:   at ./app/app.ts(file:///data/data/org.nativescript.exampleapp/files/app/bundle.js:20:107)
  System.err:   at __webpack_require__(file: app/webpack:/vvf/webpack/bootstrap:19:0)
  System.err:   at __webpack_exec__(file:///data/data/org.nativescript.exampleapp/files/app/bundle.js:3824:39)
  System.err:   at (file:///data/data/org.nativescript.exampleapp/files/app/bundle.js:3825:221)
  System.err:   at __webpack_require__.X(file: app/webpack:/vvf/webpack/runtime/startup entrypoint:6:0)
  System.err:   at (file:///data/data/org.nativescript.exampleapp/files/app/bundle.js:3825:47)
  System.err:   at (file:///data/data/org.nativescript.exampleapp/files/app/bundle.js:3830:3)
  System.err:   at require(:1:266)
 
I don't understand, what it is means! Please, help!

**Comment by ChaDmiS** [comment]
My package.json dependencies

`{
  "dependencies": {
    "@nativescript-community/ui-persistent-bottomsheet": "^0.0.24",
    "@nativescript-community/ui-svg": "^0.1.0",
    "@nativescript-community/ui-webview": "^1.4.2",
    "@nativescript/core": "~8.3.0",
    "@nativescript/google-maps": "^1.4.9",
    "@nativescript/theme": "~3.0.2",
    "@vue/composition-api": "^1.7.1",
    "nativescript-vue": "~2.9.0",
    "pinia": "^2.0.26"
  },
  "devDependencies": {
    "@nativescript/android": "8.3.1",
    "@nativescript/ios": "8.3.3",
    "@nativescript/preview-cli": "1.0.2",
    "@nativescript/types": "~8.3.0",
    "@nativescript/webpack": "~5.0.9",
    "@types/node": "~17.0.21",
    "nativescript-vue-template-compiler": "~2.9.0",
    "typescript": "~4.5.5",
    "vue": "~2.6.12"
  }
}
`

**Comment by farfromrefug** [comment]
@ChaDmiS might be due to N 8.4 changes. Can you test with N 8.4?

**Comment by ChaDmiS** [comment]
Ok. I've updated ns to 8.4 and botomsheet earned on Android.
But when I try to use `v-model="stepIndex"`, which I copied from `demo-snippets/vue/Basic.vue`, I'm getting an error :

`[Vue warn]: You may have an infinite update loop in a component render function.`

And animation is cancelled.

**Comment by farfromrefug** [comment]
@ChaDmiS sorry for the late reply. Latest build should fix this
