### ISSUE TITLE
[Android] Cannot scroll ScrollView inside bottom sheet

### ISSUE THREAD

**Issue by tommag21** [nativescript-community/ui-persistent-bottomsheet#8]
On Android I cannot scroll a ScrollView placed inside a bottom sheet. A RadListView works fine.

I have updated the test repo to test this bug: https://github.com/tommag21/bottomsheet-test

**Comment by tommag21** [comment]
Thanks. Do you have a sample or a demo I can refer to? I don't know if I have to initialise the component in the main or in webpack.config.js.

**Comment by tommag21** [comment]
I managed to override the methods `[isScrollEnabledProperty.getDefault]` `[isScrollEnabledProperty.setNative` but I got a ViewGroup error. I tried installing the plugin `@triniwiz/nativescript-nested-scrollview` but got the same error.

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: already recycled once
System.err: 
System.err: StackTrace:
System.err: java.lang.IllegalStateException: already recycled once
System.err:     at android.view.ViewGroup$TouchTarget.recycle(ViewGroup.java:8863)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2809)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at com.nativescript.gesturehandler.PageLayout.dispatchTouchEvent(PageLayout.java:135)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at com.nativescript.gesturehandler.PageLayout.dispatchTouchEvent(PageLayout.java:135)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
System.err:     at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
System.err:     at android.view.View.dispatchPointerEvent(View.java:14568)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
System.err:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
System.err:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
System.err:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8160)
System.err:     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8242)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:796)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:724)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
System.err:     at android.os.Handler.handleCallback(Handler.java:938)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:223)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
System.err: com.tns.NativeScriptException: Error: Cannot convert object to Ljava/lang/Throwable; at index 0
System.err:     at com.tns.Runtime.passExceptionToJsNative(Native Method)
System.err:     at com.tns.Runtime.passUncaughtExceptionToJs(Runtime.java:84)
System.err:     at com.tns.NativeScriptUncaughtExceptionHandler.uncaughtException(NativeScriptUncaughtExceptionHandler.java:34)
System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
System.err:     at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
```

**Comment by tommag21** [comment]
The ScrollView contains a `v-for` that renders content fetched asynchronously. Rendering the ScrollView after the content is fetched does not throw the exception, but it's still not responsive to scrolling.

At the moment I'm short on time and cannot continue debugging the nested scrollview, maybe I will continue in the future.

**Comment by fpaaske** [comment]
@tommag21 it's now the future, and if you're still investigating, maybe my experience can help :)
I've had the same issue as you (but with Angular) where the ListView/ScrollView is not responding to scrolling.

After talking to the super helpful guys (like @farfromrefug) on the NativeScript discord, this is what worked for me:

**Create the native class CustomNestedScrollView**

```
@NativeClass
class CustomNestedScrollView extends androidx.core.widget.NestedScrollView {
  private scrollEnabled: boolean;
  constructor(context: any) {
    super(context);
  }

  getScrollEnabled(): boolean {
    return this.scrollEnabled;
  }

  setScrollEnabled(enabled: boolean) {
    this.scrollEnabled = enabled;
  }
}
```

**Create the NestedScrollView to use in the markup**

```
import {ScrollView} from "@nativescript/core";

declare var androidx;

export class NestedScrollView extends ScrollView {
  createNativeView() {
    if (__ANDROID__) {
      return new CustomNestedScrollView(this._context);
    }
    return super.createNativeView();
  }
}
```

**Create the markup**

Notice the `scrollViewId` link between the BottomSheet and the NestedScrollView.

<BottomSheet [stepIndex]="stepIndex"
             (stepIndexChange)="onIndexChanged($event)"
             [steps]="bottomSheetSteps"
             scrollViewId="linkedScrollView"
>
    <GridLayout height="100%"
                width="100%"
    >
        <ListView [items]="items">
            <ng-template let-item="item">
                <StackLayout [nsRouterLink]="['/item', item.id]">
                    <Label [text]="item.name"></Label>
                </StackLayout>
            </ng-template>
        </ListView>
    </GridLayout>

    <GridLayout bottomSheet
                rows="56, 100, auto"
                columns="*"
                class="bottomSheet"
    >
        <GridLayout rows="auto" columns="*, *, *, *" row="0">
            <Button col="0" text="Step 0" class="Button" (tap)="setIndex(0)"></Button>
            <Button col="1" text="Step 1" class="Button" (tap)="setIndex(1)"></Button>
            <Button col="2" text="Step 2" class="Button" (tap)="setIndex(2)"></Button>
            <Button col="3" text="Step 3" class="Button" (tap)="setIndex(3)"></Button>
        </GridLayout>
        <StackLayout row="1" backgroundColor="orange">
            <Label text="Second step section"></Label>
        </StackLayout>
        <GridLayout row="2"
                    [height]="textViewHeight"
                    class="textView"
        >
            <NestedScrollView id="linkedScrollView" class="scrollView">
                <StackLayout>
                    <StackLayout *ngFor="let item of items">
                        <Label [text]="item.name"></Label>
                    </StackLayout>
                </StackLayout>
            </NestedScrollView>
        </GridLayout>
    </GridLayout>
</BottomSheet>
```

Now you can scroll in the list behind the bottomSheet, you can drag the bottomSheet up and down, AND you can scroll inside the bottomSheet.

**Comment by tommag21** [comment]
@fpaaske thank you! I ended up disabling the bottom sheet drag, I will try your solution asap.

**Comment by tommag21** [comment]
Gave it a try finally! That's what I did on NativeScript-Vue:

CustomNestedScrollView.ts
```
import { ScrollView } from "@nativescript/core";

export class NestedScrollView extends ScrollView {
  createNativeView() {
    if (__ANDROID__) {
      @NativeClass
      class CustomNestedScrollView extends androidx.core.widget.NestedScrollView {
        private scrollEnabled: boolean = true;

        constructor(context: any) {
          super(context);
        }

        getScrollEnabled(): boolean {
          return this.scrollEnabled;
        }

        setScrollEnabled(enabled: boolean) {
          this.scrollEnabled = enabled;
        }
      }

      return new CustomNestedScrollView(this._context);
    }
    return super.createNativeView();
  }
}

```

app.ts
```
import Vue from "nativescript-vue";
import { NestedScrollView } from "~/components/CustomNestedScrollView";

Vue.registerElement("NestedScrollView", () => NestedScrollView);
```

**Comment by tommag21** [comment]
Gave it a try finally! That's what I did on NativeScript-Vue:

CustomNestedScrollView.ts
```
import { ScrollView } from "@nativescript/core";

export class NestedScrollView extends ScrollView {
  createNativeView() {
    if (__ANDROID__) {
      @NativeClass
      class CustomNestedScrollView extends androidx.core.widget.NestedScrollView {
        private scrollEnabled: boolean = true;

        constructor(context: any) {
          super(context);
        }

        getScrollEnabled(): boolean {
          return this.scrollEnabled;
        }

        setScrollEnabled(enabled: boolean) {
          this.scrollEnabled = enabled;
        }
      }

      return new CustomNestedScrollView(this._context);
    }
    return super.createNativeView();
  }
}

```

app.ts
```
import Vue from "nativescript-vue";
import { NestedScrollView } from "~/components/CustomNestedScrollView";

Vue.registerElement("NestedScrollView", () => NestedScrollView);
```

**Comment by tommag21** [comment]
As a side note, I had to set `scrollViewId` con Android only to make the ScrollView work on iOS.

```
<BottomSheet android:scrollViewId="linkedScrollView">
```

**Comment by fpaaske** [comment]
Very nice @tommag21 👍

**Comment by CatchABus** [comment]
In the case of ListView at least, it's basically a limitation of gesturehandler plugin.
Here is a dirty sample using plain {N} gestures.
```ts
    bottomSheet.bottomSheet = assetList;

    let startY = 0;

    assetList.on("pan", (args: PanGestureEventData) => {
      if (args.state === 1) {
        // PAN START
        startY = assetList.translateY || 0;
      } else if (args.state === 2) {
        // PAN ACTIVE - update position
        const translateY = startY + args.deltaY;

        if (translateY > -bottomSheet.steps[bottomSheet.steps.length - 1]) {
          assetList.translateY = translateY;
        }
      } else if (args.state === 3) {
        let prevDist = null;
        let stepIndex = -1;

        for (let i = 0, length = bottomSheet.steps.length; i < length; i++) {
          const step = bottomSheet.steps[i];
          const dist = Math.abs(-1 * assetList.translateY - step);

          if (prevDist == null || dist < prevDist) {
            prevDist = dist;
            stepIndex = i;
          }
        }

        if (bottomSheet.stepIndex != stepIndex) {
          bottomSheet.stepIndex = stepIndex;
        } else {
          assetList.translateY = -bottomSheet.steps[stepIndex];
        }

        // PAN END - optionally do something here
        console.log("Pan ended");
      }
    });
```

@farfromrefug It'd be interesting if plugin allowed setting custom gesture handler.
